### ISSUE TITLE
Docker Image not working anymore

### ISSUE THREAD

**Issue by nachfuellbar** [mxschmitt/fritzbox_exporter#27] opened 2021-02-09 16:18 UTC
Just asking, but is something about the image not working?
I did compile the binary on my system last night and got 
```
gateway_wan_bytes_received{gateway="fritz.box"} 1.1767101047e+10
```
Or in my debugging
```
11767101047
```
With the image from last night i got
```
3181655973
```
And with the updated image from 3h before now, i get only fritzbox_exporter_collect_errors as variable and no gateway ones

PS: maybe docker registry didn't get me the recent image last night but cannot check anymore (only one tag on docker hub)

**Comment by mxschmitt** [comment] 2021-02-09 16:23
I merged d87c1a164b0a0ebf22e6a54be5a48a04aa1820e3 which should not cause such an issue, hmm thats weird.

**Comment by nachfuellbar** [comment] 2021-02-09 16:37
When accessing via curl i get this error a lot:

```
2021/02/09 17:35:34 could not call action: XML syntax error on line 1: element <HR> closed by </BODY>
```

Maybe it's helpfull for you - if not i'm willing to debug later (dunno if i could solve it because i don't know golang) ;)

**Comment by mxschmitt** [comment] 2021-02-09 16:43
I unfortunately don't have a fritz box anymore, so it's hard for me to reproduce. Will ask maybe a friend later to connect to his.

**Comment by nachfuellbar** [comment] 2021-02-12 14:55
Just tried a bit with this and the previous code
The changes in the go files in this repo don't seem to be the cause
I just compiled the "old" code with the new docker file and the same error occurs

**Comment by tillepille** [comment] 2021-07-13 21:11
I can't reproduce the error. Could be closed IMHO

**Closed as completed** 2021-07-14 09:24 UTC
